services:
  - type: web
    name: nominace-mcr-beginner-api
    runtime: python
    plan: free
    buildCommand: pip install -r api/requirements.txt && make fix aggregate
    startCommand: python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: ALLOWED_ORIGINS
        value: https://nominace-mcr-beginner-lske-2026.jan-kaspar.workers.dev
      - key: CLUB_PASSWORDS
        sync: false
      - key: TRAINER_AUTH
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_SERVICE_ID
        sync: false
